/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import javax.swing.JLabel;

/**
 *
 * @author Intel
 */
public class PanelPerfil extends javax.swing.JPanel {

    /**
     * Creates new form PanelPerfil
     */
    public PanelPerfil() {
        initComponents();
        this.setLocation(0,0);
        
        
    }

    public JLabel getLblApellidoMaterno() {
        return lblApellidoMaterno;
    }

    public void setLblApellidoMaterno(JLabel lblApellidoMaterno) {
        this.lblApellidoMaterno = lblApellidoMaterno;
    }

    public JLabel getLblApellidoPaterno() {
        return lblApellidoPaterno;
    }

    public void setLblApellidoPaterno(JLabel lblApellidoPaterno) {
        this.lblApellidoPaterno = lblApellidoPaterno;
    }

    public JLabel getLblFechaNacimiento() {
        return lblFechaNacimiento;
    }

    public void setLblFechaNacimiento(JLabel lblFechaNacimiento) {
        this.lblFechaNacimiento = lblFechaNacimiento;
    }

    public JLabel getLblNombre() {
        return lblNombre;
    }

    public void setLblNombre(JLabel lblNombre) {
        this.lblNombre = lblNombre;
    }

    public JLabel getLblNombreUsuario() {
        return lblNombreUsuario;
    }

    public void setLblNombreUsuario(JLabel lblNombreUsuario) {
        this.lblNombreUsuario = lblNombreUsuario;
    }

    public JLabel getLblTelefono() {
        return lblTelefono;
    }

    public void setLblTelefono(JLabel lblTelefono) {
        this.lblTelefono = lblTelefono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pincel editar_1.png"))); // NOI18N
        jPanel6.add(jLabel19);

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 40, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pincel editar_1.png"))); // NOI18N
        jPanel5.add(jLabel18);

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 40, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pincel editar_1.png"))); // NOI18N
        jPanel4.add(jLabel17);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 40, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pincel editar_1.png"))); // NOI18N
        jPanel3.add(jLabel16);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 40, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pincel editar_1.png"))); // NOI18N
        jPanel2.add(jLabel15);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, 40, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pincel editar_1.png"))); // NOI18N
        jPanel1.add(jLabel20);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 40, 30));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Perfil.PNG"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mi proyecto (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 20, 1060, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nombre de Usuario:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nombre:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Apellido Paterno:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Apellido Materno:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Telefono:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Fecha de Nacimiento:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        lblNombreUsuario.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblNombreUsuario.setText("jLabel9");
        add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 450, -1));

        lblFechaNacimiento.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblFechaNacimiento.setForeground(new java.awt.Color(51, 51, 51));
        lblFechaNacimiento.setText("jLabel10");
        add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 450, -1));

        lblTelefono.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(51, 51, 51));
        lblTelefono.setText("jLabel10");
        add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 450, -1));

        lblApellidoMaterno.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblApellidoMaterno.setForeground(new java.awt.Color(51, 51, 51));
        lblApellidoMaterno.setText("jLabel10");
        add(lblApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 450, -1));

        lblApellidoPaterno.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblApellidoPaterno.setForeground(new java.awt.Color(51, 51, 51));
        lblApellidoPaterno.setText("jLabel10");
        add(lblApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 450, -1));

        lblNombre.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre.setText("jLabel10");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 450, -1));

        jButton1.setText("jButton1");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JLabel lblApellidoMaterno;
    public javax.swing.JLabel lblApellidoPaterno;
    public javax.swing.JLabel lblFechaNacimiento;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblNombreUsuario;
    public javax.swing.JLabel lblTelefono;
    // End of variables declaration//GEN-END:variables
}
